name: Release by release PR
description: Create a release when a PR is merged into the release branch
inputs:
  base-branch:
    required: true
    description: The base branch
runs:
  using: "composite"
  steps:
    - name: validate event type
      run: | 
        if ${{ github.event.pull_request.merged && startsWith(github.head_ref, 'release/') }}; then
          :
        else
          echo "This action is only available in the merge event of a Release PullRequest.";
          exit 1;
        fi
      shell: bash
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        ref: ${{ inputs.base-branch }}

    - name: Parse version
      id: parse_version
      run: |
        echo "version=$(echo ${{ github.head_ref }} | sed -e 's/release\///g')" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "version=${{ steps.parse_version.outputs.version }}"
      shell: bash
    - name: Push tag
      run: |
        git tag ${{ steps.parse_version.outputs.version }}
        git push origin ${{ steps.parse_version.outputs.version }}
      shell: bash
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.parse_version.outputs.version }}
        release_name: ${{ steps.parse_version.outputs.version }}
        body: ${{ github.event.pull_request.body }}
