on:
  workflow_call:
    inputs:
      base-branch:
        required: true
        type: string
    secrets:
      github-token:
        required: true
jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ inputs.base-branch }}

      - name: Parse version
        id: parse_version
        run: |
          echo "version=$(echo ${{ github.head_ref }} | sed -e 's/release\///g')" >> $GITHUB_OUTPUT
      - run: echo "version=${{ steps.parse_version.outputs.version }}"
      - name: Push tag
        run: |
          git tag ${{ steps.parse_version.outputs.version }}
          git push origin ${{ steps.parse_version.outputs.version }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          tag_name: ${{ steps.parse_version.outputs.version }}
          release_name: ${{ steps.parse_version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
